import gdown

urls = [
"https://drive.google.com/open?id=1leCOGOA4bqbvHzgTcIYXdneyV0i2BqQT",
"https://drive.google.com/open?id=1dcTTWIss5LeZHimyC8BC-lqt-ud7l1Db",
"https://drive.google.com/open?id=1Nc_Zlzhg9_MIQaHjczyyiENSzYp9F6yt",
"https://drive.google.com/open?id=1oLTfEpG4kKfdzP41Hcib57keXletktvY",
"https://drive.google.com/open?id=1IC4jjNKiSDrSpcxZEd4wGgOGq9OyzMvI",
"https://drive.google.com/open?id=1dnDnSSZqmC3AI5V8Pavg67ds-lSN_IyD",
"https://drive.google.com/open?id=1pSvId_oPSDoAoGrsTq9Jjsn6-BU6ga6R",
"https://drive.google.com/open?id=1S6WavgLpLzHRFZwyGtAksT-0b1Ef8wvM",
"https://drive.google.com/open?id=1ETjiMzkyzSi9zmotR_5tAZR-jQmxi-lK",
"https://drive.google.com/open?id=1sQVheDo5n5VV2DJN2F00mbiKJqoY8ZXo",
"https://drive.google.com/open?id=1IOw3ojhQ_ZgexbIVRyW62qxD47j9-STD",
"https://drive.google.com/open?id=1cMTA79hkfUXojdvtLPrc-EPlTrSHLwK6",
"https://drive.google.com/open?id=1d47vmtEP5KznavmmoARLZW_ejuuKWf6R",
"https://drive.google.com/open?id=17eu-bmkQJWmf3DzwklbIIz6iGZTDKeIE",
"https://drive.google.com/open?id=19r9ib_NKZgqzUeP9PaH2_LUWXVVLL2ZX",
"https://drive.google.com/open?id=16K3R44yK2Z5jfqmYAPLMO5O9kkqUdUD6",
"https://drive.google.com/open?id=1yhV4zWHJROrnxkSgZwC4va9UZcfbTgve",
"https://drive.google.com/open?id=1uRrqKv8g_zc9szGXCaHa76sOBgYVzE1j",
"https://drive.google.com/open?id=10mbxaRYsCbTJOWVpilMYlBlvwUgZ3OIn",
"https://drive.google.com/open?id=1Ba4Ow85TkC41wMBW0p16ieDRZNFglqV8",
"https://drive.google.com/open?id=10qDtieMkrOff9kc8Z4jBJvJY81QWV6eI",
"https://drive.google.com/open?id=1Qjjc5SVgF59TUxQ2uDwS_ts3K_8gnDBB",
"https://drive.google.com/open?id=1hB22OVfk2Nkv6pAj6Dsq_sGGJkRx55d4",
"https://drive.google.com/open?id=1jbvbZ-52D245J0kjJgpH1C9gqvpE5kmt",
"https://drive.google.com/open?id=1-Bh-CDsZaEgBhGtatyyeR-tLtCg1aY8d",
"https://drive.google.com/open?id=1MXssoAqPdteFwfxPnZhAYY0VcacJ9_xJ",
"https://drive.google.com/open?id=1Emg2XODPDGoYsCQOHbCURGkz_ILDehRC",
"https://drive.google.com/open?id=1eiqWrnNNGqrVfjgfkDOcFnFil30sl9aR",
"https://drive.google.com/open?id=1GNpBtVcyUIG0_V_r7oUHj3YxVcLgoFRB",
"https://drive.google.com/open?id=1_cvM6cPSVn2SxU-Aqn1xTKCSlekk5ab2",
"https://drive.google.com/open?id=17qYGZSrnO05dxfLnWPWRQYqddBDJ9KP-",
"https://drive.google.com/open?id=1iUzSrOg0BoZFQZdfSNkt8P5qItS-tI0c",
"https://drive.google.com/open?id=1UidLvRqxcK42dWCzWWxeGFZVYaw9ch0E",
"https://drive.google.com/open?id=1zISrTbZTJqFeRV65T7IEqDE0bAV06Ttt",
"https://drive.google.com/open?id=1X1JGoJyiL_BrZVDJUk9Dq6OsV9bQ2t1E",
"https://drive.google.com/open?id=1T75WP49Snuhwu4gjLoRqK-i5XTn7o6g2",
"https://drive.google.com/open?id=1t2wImpoIXzO5TrxIZ0sGXM4_mNVb7bBS",
"https://drive.google.com/open?id=19nXlqsqF7oWUH2lBAFrWq-vaNV7lxVx6",
"https://drive.google.com/open?id=1rFCaGmNyGxufRFOJmjidruvMfi92xGGK",
"https://drive.google.com/open?id=1NoTSZl_SwTpoHMusYYiaM5A0aWztVLPw",
"https://drive.google.com/open?id=1OxUqzZp1HnzSGi3dCOzcsM4WCw-p5fLd",
"https://drive.google.com/open?id=1M2Hx7n4kmrz4w92EfkFos6Gltyw5NdaT",
"https://drive.google.com/open?id=1IUGogChTz1gNVZZJID-tbhXNWbjZG3tl",
"https://drive.google.com/open?id=1AWWKGa5I2tqEePE7gbF7g5_PsHypNTFF",
"https://drive.google.com/open?id=11xROjfLlSrriV5MzWccLF6jGGI3xn5dk",
"https://drive.google.com/open?id=1RctJxebRmkOKZYTqhEKDsK3E2i_9cQQ-",
"https://drive.google.com/open?id=1biWCAmiNluojkc3tdAf9I9AwAbbZasDt",
"https://drive.google.com/open?id=1WdCu7NRT1-dFr3mB3PjZLK02gbFqjfQa",
"https://drive.google.com/open?id=1L8IAvLWNbBxwSkrYGzdC5ALQ-mF1qakE",
"https://drive.google.com/open?id=1M4C4zlUK7EkKft3xTol8b94YThzMJW-G",
"https://drive.google.com/open?id=1YEBMtsNNxG_S3fkVuVhBExC9YPrx_oSu",
"https://drive.google.com/open?id=1Z_0x9gqTTEZaRShOdm1yaXiZ3xMC120J",
"https://drive.google.com/open?id=1kNJLSu7TZivQu0GP3chQQSFPrSrEdmh3",
"https://drive.google.com/open?id=1rQKRWy4zIWQNuQAD9jmB7xbIPiU-sqCL",
"https://drive.google.com/open?id=13MH4Hzb_mJUPDM-odXpKLN8VZ5UAYtBN",
"https://drive.google.com/open?id=1Wf9vzWF4WVw-nOsKP-sGMlHUKiqZlGQ3"
]

for url in urls:
    print("Downloading:", url)
    gdown.download(url, quiet=False, fuzzy=True)

print("SELESAI ✅")